version: '3.8'

services:
  node-app:
    build: ./node_app
    ports:
      - "8000:8000"
    env_file:
      - ./node_app/.env
    depends_on:
      - scraper
    networks:
      - backend

  scraper:
    build: ./scraper_service
    ports:
      - "5000:5000"
    networks:
      - backend

networks:
  backend:
